name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout
    uses: actions/checkout@v2

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        run: docker buildx build -t ${{ secrets.DOCKERHUB_USERNAME }}/lan-front:latest .

  login:
    name: Login to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  push:
    name: Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/lan-front:latest
